language: python
python:
  - '3.6'
  - '2.7'
install:
  - pip install .
script: nosetests
jobs:
  include:
    - stage: deploy
      if: tag =~ ^[\d\.]+$
      script: skip
      deploy:
        provider: pypi
        user: mtth
        password:
          secure: Oslw+ounXMBnCgUTF5wfXXvt/Tdxpm+pawVCP9EXdQyTO9zqmZ+aydXYhXl8Tlon/Cf4nHUWw43J67/SUx/gozSrkSRfsZ1kA9I9J6SvaxQpdHGwKTEFGuWVHNIwfRgeJ8GGPr8lBCG2LSnhRu1YPDO6R/jPdbcFbi7wMIAPjQA=
        on:
          repo: mtth/azkaban
          tags: true

